// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "signal.proto" (package "signal", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Represents a complex number with real and imaginary parts.
 *
 * @generated from protobuf message signal.Complex
 */
export interface Complex {
    /**
     * @generated from protobuf field: double real = 1;
     */
    real: number;
    /**
     * @generated from protobuf field: double imag = 2;
     */
    imag: number;
}
/**
 * @generated from protobuf message signal.MovingAverageRequest
 */
export interface MovingAverageRequest {
    /**
     * @generated from protobuf field: repeated signal.Complex signal = 1;
     */
    signal: Complex[];
    /**
     * @generated from protobuf field: int32 window_size = 2;
     */
    windowSize: number;
}
/**
 * @generated from protobuf message signal.MovingAverageResponse
 */
export interface MovingAverageResponse {
    /**
     * @generated from protobuf field: repeated signal.Complex result = 1;
     */
    result: Complex[];
}
/**
 * @generated from protobuf message signal.RuningSumRequest
 */
export interface RuningSumRequest {
    /**
     * @generated from protobuf field: repeated signal.Complex signal = 1;
     */
    signal: Complex[];
}
/**
 * @generated from protobuf message signal.RuningSumResponse
 */
export interface RuningSumResponse {
    /**
     * @generated from protobuf field: repeated signal.Complex result = 1;
     */
    result: Complex[];
}
/**
 * @generated from protobuf message signal.FirstDifferenceRequest
 */
export interface FirstDifferenceRequest {
    /**
     * @generated from protobuf field: repeated signal.Complex signal = 1;
     */
    signal: Complex[];
}
/**
 * @generated from protobuf message signal.FirstDifferenceResponse
 */
export interface FirstDifferenceResponse {
    /**
     * @generated from protobuf field: repeated signal.Complex result = 1;
     */
    result: Complex[];
}
/**
 * @generated from protobuf message signal.IFFTRequest
 */
export interface IFFTRequest {
    /**
     * @generated from protobuf field: repeated signal.Complex signal = 1;
     */
    signal: Complex[];
}
/**
 * @generated from protobuf message signal.IFFTResponse
 */
export interface IFFTResponse {
    /**
     * @generated from protobuf field: repeated signal.Complex result = 1;
     */
    result: Complex[];
}
/**
 * @generated from protobuf message signal.FastWaveletTransformHaarRequest
 */
export interface FastWaveletTransformHaarRequest {
    /**
     * @generated from protobuf field: repeated signal.Complex signal = 1;
     */
    signal: Complex[];
}
/**
 * @generated from protobuf message signal.FastWaveletTransformHaarResponse
 */
export interface FastWaveletTransformHaarResponse {
    /**
     * @generated from protobuf field: repeated signal.Complex approximation = 1;
     */
    approximation: Complex[];
    /**
     * @generated from protobuf field: repeated signal.Complex detail = 2;
     */
    detail: Complex[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Complex$Type extends MessageType<Complex> {
    constructor() {
        super("signal.Complex", [
            { no: 1, name: "real", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "imag", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<Complex>): Complex {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.real = 0;
        message.imag = 0;
        if (value !== undefined)
            reflectionMergePartial<Complex>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Complex): Complex {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double real */ 1:
                    message.real = reader.double();
                    break;
                case /* double imag */ 2:
                    message.imag = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Complex, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double real = 1; */
        if (message.real !== 0)
            writer.tag(1, WireType.Bit64).double(message.real);
        /* double imag = 2; */
        if (message.imag !== 0)
            writer.tag(2, WireType.Bit64).double(message.imag);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.Complex
 */
export const Complex = new Complex$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MovingAverageRequest$Type extends MessageType<MovingAverageRequest> {
    constructor() {
        super("signal.MovingAverageRequest", [
            { no: 1, name: "signal", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex },
            { no: 2, name: "window_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MovingAverageRequest>): MovingAverageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signal = [];
        message.windowSize = 0;
        if (value !== undefined)
            reflectionMergePartial<MovingAverageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MovingAverageRequest): MovingAverageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex signal */ 1:
                    message.signal.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 window_size */ 2:
                    message.windowSize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MovingAverageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex signal = 1; */
        for (let i = 0; i < message.signal.length; i++)
            Complex.internalBinaryWrite(message.signal[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 window_size = 2; */
        if (message.windowSize !== 0)
            writer.tag(2, WireType.Varint).int32(message.windowSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.MovingAverageRequest
 */
export const MovingAverageRequest = new MovingAverageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MovingAverageResponse$Type extends MessageType<MovingAverageResponse> {
    constructor() {
        super("signal.MovingAverageResponse", [
            { no: 1, name: "result", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<MovingAverageResponse>): MovingAverageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = [];
        if (value !== undefined)
            reflectionMergePartial<MovingAverageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MovingAverageResponse): MovingAverageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex result */ 1:
                    message.result.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MovingAverageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex result = 1; */
        for (let i = 0; i < message.result.length; i++)
            Complex.internalBinaryWrite(message.result[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.MovingAverageResponse
 */
export const MovingAverageResponse = new MovingAverageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuningSumRequest$Type extends MessageType<RuningSumRequest> {
    constructor() {
        super("signal.RuningSumRequest", [
            { no: 1, name: "signal", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<RuningSumRequest>): RuningSumRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signal = [];
        if (value !== undefined)
            reflectionMergePartial<RuningSumRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuningSumRequest): RuningSumRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex signal */ 1:
                    message.signal.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuningSumRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex signal = 1; */
        for (let i = 0; i < message.signal.length; i++)
            Complex.internalBinaryWrite(message.signal[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.RuningSumRequest
 */
export const RuningSumRequest = new RuningSumRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuningSumResponse$Type extends MessageType<RuningSumResponse> {
    constructor() {
        super("signal.RuningSumResponse", [
            { no: 1, name: "result", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<RuningSumResponse>): RuningSumResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = [];
        if (value !== undefined)
            reflectionMergePartial<RuningSumResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuningSumResponse): RuningSumResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex result */ 1:
                    message.result.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuningSumResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex result = 1; */
        for (let i = 0; i < message.result.length; i++)
            Complex.internalBinaryWrite(message.result[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.RuningSumResponse
 */
export const RuningSumResponse = new RuningSumResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FirstDifferenceRequest$Type extends MessageType<FirstDifferenceRequest> {
    constructor() {
        super("signal.FirstDifferenceRequest", [
            { no: 1, name: "signal", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<FirstDifferenceRequest>): FirstDifferenceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signal = [];
        if (value !== undefined)
            reflectionMergePartial<FirstDifferenceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FirstDifferenceRequest): FirstDifferenceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex signal */ 1:
                    message.signal.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FirstDifferenceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex signal = 1; */
        for (let i = 0; i < message.signal.length; i++)
            Complex.internalBinaryWrite(message.signal[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.FirstDifferenceRequest
 */
export const FirstDifferenceRequest = new FirstDifferenceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FirstDifferenceResponse$Type extends MessageType<FirstDifferenceResponse> {
    constructor() {
        super("signal.FirstDifferenceResponse", [
            { no: 1, name: "result", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<FirstDifferenceResponse>): FirstDifferenceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = [];
        if (value !== undefined)
            reflectionMergePartial<FirstDifferenceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FirstDifferenceResponse): FirstDifferenceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex result */ 1:
                    message.result.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FirstDifferenceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex result = 1; */
        for (let i = 0; i < message.result.length; i++)
            Complex.internalBinaryWrite(message.result[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.FirstDifferenceResponse
 */
export const FirstDifferenceResponse = new FirstDifferenceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IFFTRequest$Type extends MessageType<IFFTRequest> {
    constructor() {
        super("signal.IFFTRequest", [
            { no: 1, name: "signal", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<IFFTRequest>): IFFTRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signal = [];
        if (value !== undefined)
            reflectionMergePartial<IFFTRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IFFTRequest): IFFTRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex signal */ 1:
                    message.signal.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IFFTRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex signal = 1; */
        for (let i = 0; i < message.signal.length; i++)
            Complex.internalBinaryWrite(message.signal[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.IFFTRequest
 */
export const IFFTRequest = new IFFTRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IFFTResponse$Type extends MessageType<IFFTResponse> {
    constructor() {
        super("signal.IFFTResponse", [
            { no: 1, name: "result", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<IFFTResponse>): IFFTResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = [];
        if (value !== undefined)
            reflectionMergePartial<IFFTResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IFFTResponse): IFFTResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex result */ 1:
                    message.result.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IFFTResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex result = 1; */
        for (let i = 0; i < message.result.length; i++)
            Complex.internalBinaryWrite(message.result[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.IFFTResponse
 */
export const IFFTResponse = new IFFTResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FastWaveletTransformHaarRequest$Type extends MessageType<FastWaveletTransformHaarRequest> {
    constructor() {
        super("signal.FastWaveletTransformHaarRequest", [
            { no: 1, name: "signal", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<FastWaveletTransformHaarRequest>): FastWaveletTransformHaarRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signal = [];
        if (value !== undefined)
            reflectionMergePartial<FastWaveletTransformHaarRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FastWaveletTransformHaarRequest): FastWaveletTransformHaarRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex signal */ 1:
                    message.signal.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FastWaveletTransformHaarRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex signal = 1; */
        for (let i = 0; i < message.signal.length; i++)
            Complex.internalBinaryWrite(message.signal[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.FastWaveletTransformHaarRequest
 */
export const FastWaveletTransformHaarRequest = new FastWaveletTransformHaarRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FastWaveletTransformHaarResponse$Type extends MessageType<FastWaveletTransformHaarResponse> {
    constructor() {
        super("signal.FastWaveletTransformHaarResponse", [
            { no: 1, name: "approximation", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex },
            { no: 2, name: "detail", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Complex }
        ]);
    }
    create(value?: PartialMessage<FastWaveletTransformHaarResponse>): FastWaveletTransformHaarResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.approximation = [];
        message.detail = [];
        if (value !== undefined)
            reflectionMergePartial<FastWaveletTransformHaarResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FastWaveletTransformHaarResponse): FastWaveletTransformHaarResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated signal.Complex approximation */ 1:
                    message.approximation.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated signal.Complex detail */ 2:
                    message.detail.push(Complex.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FastWaveletTransformHaarResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated signal.Complex approximation = 1; */
        for (let i = 0; i < message.approximation.length; i++)
            Complex.internalBinaryWrite(message.approximation[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated signal.Complex detail = 2; */
        for (let i = 0; i < message.detail.length; i++)
            Complex.internalBinaryWrite(message.detail[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message signal.FastWaveletTransformHaarResponse
 */
export const FastWaveletTransformHaarResponse = new FastWaveletTransformHaarResponse$Type();
/**
 * @generated ServiceType for protobuf service signal.SignalService
 */
export const SignalService = new ServiceType("signal.SignalService", [
    { name: "ComputeMovingAverage", options: {}, I: MovingAverageRequest, O: MovingAverageResponse },
    { name: "ComputeRuningSum", options: {}, I: RuningSumRequest, O: RuningSumResponse },
    { name: "ComputeFirstDifference", options: {}, I: FirstDifferenceRequest, O: FirstDifferenceResponse },
    { name: "ComputeIFFT", options: {}, I: IFFTRequest, O: IFFTResponse },
    { name: "ComputeFastWaveletTransformHaar", options: {}, I: FastWaveletTransformHaarRequest, O: FastWaveletTransformHaarResponse }
]);
