// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "signal.proto" (package "signal", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SignalService } from "./signal";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { MovingAverageResponse } from "./signal";
import type { MovingAverageRequest } from "./signal";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * The signal service definition.
 *
 * @generated from protobuf service signal.SignalService
 */
export interface ISignalServiceClient {
    /**
     * @generated from protobuf rpc: ComputeMovingAverage(signal.MovingAverageRequest) returns (signal.MovingAverageResponse);
     */
    computeMovingAverage(input: MovingAverageRequest, options?: RpcOptions): UnaryCall<MovingAverageRequest, MovingAverageResponse>;
}
/**
 * The signal service definition.
 *
 * @generated from protobuf service signal.SignalService
 */
export class SignalServiceClient implements ISignalServiceClient, ServiceInfo {
    typeName = SignalService.typeName;
    methods = SignalService.methods;
    options = SignalService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ComputeMovingAverage(signal.MovingAverageRequest) returns (signal.MovingAverageResponse);
     */
    computeMovingAverage(input: MovingAverageRequest, options?: RpcOptions): UnaryCall<MovingAverageRequest, MovingAverageResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MovingAverageRequest, MovingAverageResponse>("unary", this._transport, method, opt, input);
    }
}
